<?php

namespace App\Entity\Catalog\Product;

use App\Entity\BaseEntity;
use App\Entity\Type\BaseType;
use App\Repository\Catalog\Product\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product extends BaseEntity
{
    public function setType(?BaseType $type): static
    {
        if (!$type instanceof ProductType) {
            throw new InvalidArgumentException();
        }
        return parent::setType($type); // TODO: Change the autogenerated stub
    }
}
