version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pet-cms
      POSTGRES_DB: pet-cms
      POSTGRES_USER: pet-cms
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5424:5432"
  db_test:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pet-cms-test
      POSTGRES_DB: pet-cms-test
      POSTGRES_USER: pet-cms-test
    volumes:
      - ./db-data-test:/var/lib/postgresql/data
    ports:
      - "5425:5432"
