version: '3.8'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8054:8080"
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pet-cms
      POSTGRES_DB: pet-cms
      POSTGRES_USER: pet-cms
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5424:5432"
  db_test:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pet-cms-test
      POSTGRES_DB: pet-cms-test
      POSTGRES_USER: pet-cms-test
    volumes:
      - ./db-data-test:/var/lib/postgresql/data
    ports:
      - "5425:5432"
  memcached:
    image: memcached:1.6.21-alpine
    restart: unless-stopped
    ports:
      - '11212:11211'
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6380:6379'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '127.0.0.1:6381:8001'