<?php

namespace App\Entity\Guide;

use App\Entity\BaseEntity;
use App\Entity\Type\BaseType;
use App\Repository\Guide\GuideRepository;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;

#[ORM\Entity(repositoryClass: GuideRepository::class)]
class Guide extends BaseEntity
{
    public function setType(?BaseType $type): static
    {
        if (!$type instanceof GuideType) {
            throw new InvalidArgumentException();
        }
        return parent::setType($type); // TODO: Change the autogenerated stub
    }
}
